"""create service jobs table

Revision ID: 0d11e3f0bd11
Revises: 10a5706c925a
Create Date: 2026-07-02 15:39:05.588074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d11e3f0bd11'
down_revision: Union[str, Sequence[str], None] = '10a5706c925a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_jobs',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.Enum('ONSITE_SERVICE', 'ONSITE_REPAIR', 'ONSITE_CALIBRATION', 'WORKSHOP_REPAIR', name='job_type'), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'AWAITING_INSPECTION', 'READY_FOR_QUOTE', 'AWAITING_CUSTOMER_APPROVAL', 'WAITING_FOR_PARTS', 'RETURN_TO_FIT', 'IN_REPAIR', 'READY_FOR_RETURN', 'COMPLETED', 'CLOSED', name='job_status'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_service_jobs_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_jobs')),
    sa.UniqueConstraint('reference_number', name=op.f('uq_service_jobs_reference_number'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_jobs')
    # ### end Alembic commands ###
