"""create equipment table

Revision ID: 10a5706c925a
Revises: 92c78ff39b69
Create Date: 2026-07-02 14:52:07.273552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a5706c925a'
down_revision: Union[str, Sequence[str], None] = '92c78ff39b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('primary_contact_user_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_equipment_company_id_companies')),
    sa.ForeignKeyConstraint(['primary_contact_user_id'], ['users.id'], name=op.f('fk_equipment_primary_contact_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment')
    # ### end Alembic commands ###
