"""add user job title and sir initials

Revision ID: 2fda6ac88cbf
Revises: 13fa3965ce8b
Create Date: 2026-07-02 23:03:29.730117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fda6ac88cbf'
down_revision: Union[str, Sequence[str], None] = '13fa3965ce8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_title', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('sir_initials', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sir_initials')
    op.drop_column('users', 'job_title')
    # ### end Alembic commands ###
