"""create service job item notes

Revision ID: 60a562f697d5
Revises: bd1c65785762
Create Date: 2026-07-06 00:11:03.940596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60a562f697d5'
down_revision: Union[str, Sequence[str], None] = 'bd1c65785762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_job_item_notes',
    sa.Column('service_job_item_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('is_customer_visible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_service_job_item_notes_author_user_id_users')),
    sa.ForeignKeyConstraint(['service_job_item_id'], ['service_job_items.id'], name=op.f('fk_service_job_item_notes_service_job_item_id_service_job_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_job_item_notes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_job_item_notes')
    # ### end Alembic commands ###
