"""create service job items table

Revision ID: 63655ad49f6a
Revises: 0d11e3f0bd11
Create Date: 2026-07-02 15:49:12.804262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63655ad49f6a'
down_revision: Union[str, Sequence[str], None] = '0d11e3f0bd11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_job_items',
    sa.Column('service_job_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('contact_user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_engineer_id', sa.Integer(), nullable=True),
    sa.Column('sir_number', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_engineer_id'], ['users.id'], name=op.f('fk_service_job_items_assigned_engineer_id_users')),
    sa.ForeignKeyConstraint(['contact_user_id'], ['users.id'], name=op.f('fk_service_job_items_contact_user_id_users')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_service_job_items_equipment_id_equipment')),
    sa.ForeignKeyConstraint(['service_job_id'], ['service_jobs.id'], name=op.f('fk_service_job_items_service_job_id_service_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_job_items')),
    sa.UniqueConstraint('sir_number', name=op.f('uq_service_job_items_sir_number'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_job_items')
    # ### end Alembic commands ###
