"""make user staff fields optional

Revision ID: 93ee6677ea43
Revises: b008f7ce8c7d
Create Date: 2026-07-03 11:54:51.442015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ee6677ea43'
down_revision: Union[str, Sequence[str], None] = 'b008f7ce8c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'job_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'sir_initials',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sir_initials',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('users', 'job_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
