"""add user authentication fields

Revision ID: b008f7ce8c7d
Revises: 76de8deee924
Create Date: 2026-07-03 10:32:04.512589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b008f7ce8c7d'
down_revision: Union[str, Sequence[str], None] = '76de8deee924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###s
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column(
        'users',
        sa.Column('is_email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    )
    op.add_column('users', sa.Column('activated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'activated_at')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
