"""create service job item timeline

Revision ID: bd1c65785762
Revises: f5d4a0cc0337
Create Date: 2026-07-05 20:51:08.644535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'bd1c65785762'
down_revision: Union[str, Sequence[str], None] = 'f5d4a0cc0337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_job_item_timeline',
    sa.Column('service_job_item_id', sa.Integer(), nullable=False),
    sa.Column("status",postgresql.ENUM(name="service_job_item_status",create_type=False,),nullable=False,),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_service_job_item_timeline_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['service_job_item_id'], ['service_job_items.id'], name=op.f('fk_service_job_item_timeline_service_job_item_id_service_job_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_job_item_timeline'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_job_item_timeline')
    # ### end Alembic commands ###
